sonar.projectKey=7_3_hd_task
sonar.projectName=7.3HDTask
sonar.sources=.
sonar.python.version=3.11
sonar.exclusions=**/tests/**,**/.venv/**,**/__pycache__/**
sonar.tests=tests
sonar.python.xunit.reportPath=results/junit.xml